### ISSUE TITLE
REFACTOR: Remove the use of `vue-cli-electron-builder` to use `vue-cli` and `electron-builder` separately

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1870]
vue-cli-electron-builder is no longer maintained. Also twisting up these build tools isn't really needed, we should be able to accomplish the same thing without this weird integration.

We just need to do a couple of things:
1. Run the electron app
2. Start a dev webpack server using vue-cli

This is basically what the package does anyway

So we can use something like parallel, or npm-run-all. This should looks similar to how it's done in actual I'd guess: https://github.com/actualbudget/actual/blob/master/package.json#L22C41-L22C41

## TODOs

- [ ] Move electron-builder config out of vue.config.js and into a supported place
- [ ] Remove vue-cli-electron-builder
- [ ] Update package.json build and serve scripts to work with electron builder directly
- [ ] Update any github actions workflows to use electron-builder directly (or a build script you create)

## Stuff that should work afterwards

- [ ] Dev electron mode
- [ ] Manual `electron:build` triggering
- [ ] Github Actions workflows

Make sure to check all environment variables, or other magic done by vue-cli-electron-builder
