### ISSUE TITLE
REFACTOR: Migrate from vue-cli to Vite (stay on Vue2)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1872]
vue-cli and webpack are deprecated. Vite is the new supported way to build Vue.js apps.

This is blocked on: #1871, #1870, #1840.

UNKNOWN: Will our Vue2 app build properly with Vite? See https://github.com/vitejs/vite-plugin-vue2 - it has not been released since 2022. Hopefully it still works before we move to Vue@3.

## TODO

- [ ] Replicate the webpack external dependencies config in Vite somehow
- [ ] Replicate the SaSS building we have in Vite somehow
- [ ] Re-write our serve and build scripts to use vite and not vue-cli
- [ ] Remove all the webpack dependencies from package.json
- [ ] Check everything works, it might not.

**Comment by rathboma** [comment]
This is BLOCKED on #1840

- Vite 5 requires Node 18
- Electron 18 is Node 16
- Using Electron 20+ will BREAK native deps in the front-end
- So we need a separate process with native deps before upgrading

**Comment by yooouuri** [comment]
@rathboma Hey, im the person from reddit and willing to help migrate, what native devs does Electron 20 break in the frontend?

**Comment by rathboma** [comment]
Hi!

Well for us, the better-sqlite package. 1/3 times it just bricks the app. I need to move to a multi process architecture
