### ISSUE TITLE
4.2 Release checklist

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2060]
- [x] Publish CE on GitHub
- [x] Publish UE on GitHub
- [ ] Publish a release post to the blog
- [ ] Send an email newsletter announcing the release
- [ ] Update the website to include a Firebird logo + a Firebird page
- [ ] Make a 4.0+ video walkthrough without the weird flickering
