### ISSUE TITLE
V5 Things to test checklist

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2362]
- [x] Does OracleDB work when the app is built
- [x] Is the oracle driver using fat or thin mode now?
- [ ] Can we connect to a database running in WSL from the windows app?
- [x] Do all the drivers work?
- [x] Fix titlebars in `native` window mode (Windows, Linux) (fixed by day ie native titlebar is gonzo)
- [x] Changing editor keymap doesn't switch the keymap immediately (fixed by day)
- [x] Unpinning saved connections doesn't work (fixed by day)
- [ ] Pinned entity icon lags behind actions 
- [x] Query status bar not showing any details (Will) (https://github.com/beekeeper-studio/beekeeper-studio/pull/2383)
- [x] Icon for dbEntitiy drop/truncate tables incorrect (Will) (https://github.com/beekeeper-studio/beekeeper-studio/pull/2399)   
- [x] Seems to be a race condition in the query editor. The size is sometimes not set properly, and the content isn't loaded properly (I notice it specifically when it is the tab that is first loaded when connecting and when opening a new query editor tab) (fixed by day)
- [ ] ...add more here

**Comment by wmontgomery** [comment]
Replicate: Go to a recently used connection (not saved) and attempt to save it. The following happens
![save-error](https://github.com/user-attachments/assets/71075d30-470a-41e2-8af4-d44ddaadad60)

**Comment by wmontgomery** [comment]
Replicate: pin some tables, click "refresh tables" button
![refresh-error](https://github.com/user-attachments/assets/59c72307-4b44-4add-991f-0e06cc0fffef)
